# Generated by Django 5.2 on 2025-04-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spare_parts/'),
        ),
    ]
