# Generated by Django 5.2 on 2025-05-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_role_repairshop_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
